import type { Metadata } from "next";
import { Inter, Kumbh_Sans } from "next/font/google";
import "./globals.css";
import GlobalContextProvider from "./Context";
import Header from "./components/Header";


const kumbhSans = Kumbh_Sans({
  subsets: ["latin"],
  weight: ["400", "700", "300"],
});

export const metadata: Metadata = {
  title: "devjobs-web-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kumbhSans.className}>
        <GlobalContextProvider>
          <div className="afterbody ">
          <Header />
            
            {children}</div>
        </GlobalContextProvider>
        
      </body>
    </html>
  );
}
